version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Pranc1ngPegasus"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Pranc1ngPegasus"
  - package-ecosystem: "github-actions"
    directory: '/'
    schedule:
      interval: "daily"
    reviewers:
      - "Pranc1ngPegasus"
